### ISSUE TITLE
Style change for status messages

### ISSUE THREAD

**Issue by tjrana** [sn-extensions/focus-theme#3]
Status messages such as "Decrypting notes..." and "Syncing..." currently appear as black text on a white background. This can be changed to white text on a purple background to match the theme.

**Comment by atmoio** [comment]
Is this on mobile? Any screenshots?

**Comment by tjrana** [comment]
> Is this on mobile?

Yes, this on Standard Notes for iOS.

> Any screenshots?

![screenshot](https://user-images.githubusercontent.com/1413468/46511324-871a2d00-c83d-11e8-908f-6fcc6bee61f8.png)

**Comment by tjrana** [comment]
The Standard Notes UI has since been updated. This issue has been resolved.
